{% set name = "welltestpy" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d697bf68d6d05265e50247ac4e64a12e3676a2e9cd967d2f18bf1c3e750119c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools >=45
    - setuptools_scm >=3.4
  run:
    - python >=3.5
    - anaflow >=1.0.0
    - numpy >=1.14.5
    - pandas >=0.23.2
    - scipy >=1.1.0
    - spotpy >=1.5.0
    - matplotlib-base

test:
  imports:
    - welltestpy
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/GeoStat-Framework/welltestpy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: welltestpy - package to handle well-based Field-campaigns.
  doc_url: https://welltestpy.readthedocs.io/
  dev_url: https://github.com/GeoStat-Framework/welltestpy

extra:
  recipe-maintainers:
    - MuellerSeb
